---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      shell: "echo Welcome to Saswata's Server - created with DevOps Pipeline v1 > /var/www/html/index.html"
    - name: start service
      service: name=httpd state=started
    - name: add user
      user: name=gagandeep state=present
